### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by NRGJobro** [Laamy/InternalMinecraftClient#8]
https://user-images.githubusercontent.com/85864573/140655926-842a2559-b352-4085-9ea4-dfce0ab540e5.png
I cant build this, and I have no idea why. I tried building in debug, and in release and I get this error.

**Comment by de-Gamers638** [comment]
Reinstall the minhook pavkage and rename the libMinHookx64 144.mdd (or somethink like that) to libMinHook.mdd

**Comment by Intoprelised** [comment]
Call me I can show you

**Comment by Laamy** [comment]
YourProjectFolder/packages/MinHook.1.3.3/lin/native then rename libMinHook-x64-v141-mtd.lib to libMinHook.lib and then try build again
